general: 
    seed: 123
    logdir_base: "{{project_root}}/tensorboard"
    note: "high lr is bad. keep it less than .0002"

model:
    name: "autolm"
    trgt_vocab_size: 50000
    ckpt_dir: "{{project_root}}/checkpoints"
    seq_len: 512
    embedding_dim: 1024
    num_decoder_layers: 12
    num_hidden_layers: 2
    decoder_dropout: 0.1
    mlp_dropout: 0
    min_freq: 1
    nhead: 8
    dim_feed_forward: 1024
    device: 
        - "cuda:0"
        - "cuda:1"
    save_checkpoint: True
    keep_higher_eval: False
    evaluate: True

optim:
    lr: 8.0e-6
    weight_decay: 1.0e-5
    beta1: .9
    beta2: .999
    eps: 1.0e-8
    scheduler_freq: 1000
    clip_max_norm: 1.5

data: 
    num_proc: 20
    num_shards: 1
    cache_dir: "{{home}}/.cache/huggingface"
    shuffle: True
    batch_size: 23
    num_epochs: 3
    eval_freq: 300
    log_freq: 10
    tknzr_from_scratch: False
